/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import Controller.LoginController;
import Utility.UIData;
/**
 *
 * @author nabillaaura
 */
public class Login extends javax.swing.JFrame {

    private Controller.LoginController controller;
    
    public Login(LoginController controller) {
        this.controller = controller;
        initComponents();
    }
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        B_SignUpMember = new javax.swing.JButton();
        B_Login = new javax.swing.JButton();
        B_SignUpTutor = new javax.swing.JButton();
        TF_Username = new javax.swing.JTextField();
        TF_Password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        B_SignUpMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_RegistrationMember.png"))); // NOI18N
        B_SignUpMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_SignUpMemberActionPerformed(evt);
            }
        });
        jPanel1.add(B_SignUpMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 450, 90, 40));

        B_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_SignIn.png"))); // NOI18N
        B_Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_LoginActionPerformed(evt);
            }
        });
        jPanel1.add(B_Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 341, 110, -1));

        B_SignUpTutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_RegistrationTutor.png"))); // NOI18N
        B_SignUpTutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_SignUpTutorActionPerformed(evt);
            }
        });
        jPanel1.add(B_SignUpTutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 100, 40));

        TF_Username.setBackground(new java.awt.Color(224, 187, 218));
        TF_Username.setMaximumSize(new java.awt.Dimension(6, 22));
        TF_Username.setOpaque(false);
        jPanel1.add(TF_Username, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 210, 300, 30));

        TF_Password.setBackground(new java.awt.Color(224, 187, 218));
        TF_Password.setMaximumSize(new java.awt.Dimension(6, 22));
        TF_Password.setOpaque(false);
        TF_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TF_PasswordActionPerformed(evt);
            }
        });
        jPanel1.add(TF_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 290, 300, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/Background_Login.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_LoginActionPerformed
        String username = TF_Username.getText();
        String password = TF_Password.getText();
        if(!username.isEmpty() && !password.isEmpty())
            controller.Login(username, password);
    }//GEN-LAST:event_B_LoginActionPerformed

    private void TF_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TF_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TF_PasswordActionPerformed

    private void B_SignUpMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_SignUpMemberActionPerformed
       controller.MoveToSignUp(true);
    }//GEN-LAST:event_B_SignUpMemberActionPerformed

    private void B_SignUpTutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_SignUpTutorActionPerformed
        controller.MoveToSignUp(false);
    }//GEN-LAST:event_B_SignUpTutorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Login;
    private javax.swing.JButton B_SignUpMember;
    private javax.swing.JButton B_SignUpTutor;
    private javax.swing.JPasswordField TF_Password;
    private javax.swing.JTextField TF_Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
