/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.MemberController;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author nabillaaura
 */
public class Pembayaran extends javax.swing.JFrame {

    /**
     * Creates new form Pembayaran
     */
    public final JFileChooser openFileChooser;
    private File proofFile;
    
    private MemberController controller;

    public Pembayaran(MemberController controller) {
        this.controller = controller;
        initComponents();
        openFileChooser = new JFileChooser();
        Initialize();
    }
    
    public Pembayaran() {
        initComponents();
        openFileChooser = new JFileChooser();
        Initialize();
    }
    
    private void Initialize(){
        openFileChooser.setCurrentDirectory(new File("c:\\tmp"));
        openFileChooser.setFileFilter(new FileNameExtensionFilter("Image File", "jpg"));
        openFileChooser.setFileFilter(new FileNameExtensionFilter("PDF File", "pdf"));
        openFileChooser.setAcceptAllFileFilterUsed(false);
        RadioButton_PaketLangganan.setVisible(false);
        RadioButton_PaketSantai.setVisible(false);
        RadioButton_PaketNgambis.setVisible(false);
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BGroup_Subscription = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        B_PaketNgambis = new javax.swing.JButton();
        B_PaketSantai = new javax.swing.JButton();
        B_PaketLangganan = new javax.swing.JButton();
        Label_UploadFile = new javax.swing.JLabel();
        B_UploadFile = new javax.swing.JButton();
        CB_Syarat = new javax.swing.JCheckBox();
        B_Next = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        RadioButton_PaketNgambis = new javax.swing.JRadioButton();
        RadioButton_PaketLangganan = new javax.swing.JRadioButton();
        RadioButton_PaketSantai = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        B_PaketNgambis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_SubscriptionPaketNgambis.png"))); // NOI18N
        B_PaketNgambis.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(75, 77, 88), 5, true));
        B_PaketNgambis.setBorderPainted(false);
        B_PaketNgambis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_PaketNgambisMouseClicked(evt);
            }
        });
        B_PaketNgambis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_PaketNgambisActionPerformed(evt);
            }
        });
        B_PaketNgambis.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                B_PaketNgambisPropertyChange(evt);
            }
        });
        jPanel1.add(B_PaketNgambis, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 130, 140));

        B_PaketSantai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_SubscriptionPaketSantai.png"))); // NOI18N
        B_PaketSantai.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(75, 77, 88), 5, true));
        B_PaketSantai.setBorderPainted(false);
        B_PaketSantai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_PaketSantaiMouseClicked(evt);
            }
        });
        B_PaketSantai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_PaketSantaiActionPerformed(evt);
            }
        });
        jPanel1.add(B_PaketSantai, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 130, 140));

        B_PaketLangganan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_SubscriptionPaketLangganan.png"))); // NOI18N
        B_PaketLangganan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(75, 77, 88), 5, true));
        B_PaketLangganan.setBorderPainted(false);
        B_PaketLangganan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B_PaketLanggananMouseClicked(evt);
            }
        });
        B_PaketLangganan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_PaketLanggananActionPerformed(evt);
            }
        });
        jPanel1.add(B_PaketLangganan, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 130, 140));

        Label_UploadFile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(Label_UploadFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, 200, 30));

        B_UploadFile.setBackground(new java.awt.Color(204, 204, 204));
        B_UploadFile.setText("Select File");
        B_UploadFile.setBorder(null);
        B_UploadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_UploadFileActionPerformed(evt);
            }
        });
        jPanel1.add(B_UploadFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 80, 30));

        CB_Syarat.setBackground(new java.awt.Color(224, 187, 218));
        CB_Syarat.setText("Saya menyetujui syarat dan ketentuan yang berlaku");
        CB_Syarat.setToolTipText("");
        CB_Syarat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_SyaratActionPerformed(evt);
            }
        });
        jPanel1.add(CB_Syarat, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 370, 35));

        B_Next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Next_Gray.png"))); // NOI18N
        B_Next.setBorder(null);
        B_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_NextActionPerformed(evt);
            }
        });
        jPanel1.add(B_Next, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/Background_Subscription.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 510));

        BGroup_Subscription.add(RadioButton_PaketNgambis);
        RadioButton_PaketNgambis.setText("jRadioButton1");
        RadioButton_PaketNgambis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton_PaketNgambisActionPerformed(evt);
            }
        });
        jPanel1.add(RadioButton_PaketNgambis, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));

        BGroup_Subscription.add(RadioButton_PaketLangganan);
        RadioButton_PaketLangganan.setText("jRadioButton1");
        RadioButton_PaketLangganan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton_PaketLanggananActionPerformed(evt);
            }
        });
        jPanel1.add(RadioButton_PaketLangganan, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 290, -1, -1));

        BGroup_Subscription.add(RadioButton_PaketSantai);
        RadioButton_PaketSantai.setText("jRadioButton1");
        RadioButton_PaketSantai.setBorderPainted(true);
        RadioButton_PaketSantai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton_PaketSantaiActionPerformed(evt);
            }
        });
        jPanel1.add(RadioButton_PaketSantai, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_PaketLanggananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_PaketLanggananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_PaketLanggananActionPerformed

    private void CB_SyaratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_SyaratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_SyaratActionPerformed

    private void B_PaketSantaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_PaketSantaiMouseClicked
        // TODO add your handling code here:
        B_PaketSantai.setBorderPainted(true);
        B_PaketNgambis.setBorderPainted(false);
        B_PaketLangganan.setBorderPainted(false);
        RadioButton_PaketSantai.setSelected(true);

    }//GEN-LAST:event_B_PaketSantaiMouseClicked

    private void B_PaketNgambisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_PaketNgambisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_PaketNgambisActionPerformed

    private void B_PaketNgambisPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_B_PaketNgambisPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_B_PaketNgambisPropertyChange

    private void B_PaketSantaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_PaketSantaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_PaketSantaiActionPerformed

    private void RadioButton_PaketSantaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton_PaketSantaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButton_PaketSantaiActionPerformed

    private void RadioButton_PaketNgambisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton_PaketNgambisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButton_PaketNgambisActionPerformed

    private void RadioButton_PaketLanggananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton_PaketLanggananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButton_PaketLanggananActionPerformed

    private void B_PaketNgambisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_PaketNgambisMouseClicked
        // TODO add your handling code here:
        B_PaketSantai.setBorderPainted(false);
        B_PaketNgambis.setBorderPainted(true);
        B_PaketLangganan.setBorderPainted(false);
        RadioButton_PaketNgambis.setSelected(true);
    }//GEN-LAST:event_B_PaketNgambisMouseClicked

    private void B_PaketLanggananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_PaketLanggananMouseClicked
        // TODO add your handling code here:
        B_PaketSantai.setBorderPainted(false);
        B_PaketNgambis.setBorderPainted(false);
        B_PaketLangganan.setBorderPainted(true);
        RadioButton_PaketLangganan.setSelected(true);
    }//GEN-LAST:event_B_PaketLanggananMouseClicked

    private String getPaket(){
        if (RadioButton_PaketLangganan.isSelected()) {
            return "Langganan";
        }
        else if (RadioButton_PaketNgambis.isSelected()) {
            return "Ngambis";
        }
        if (RadioButton_PaketSantai.isSelected()) {
            return "Santai";
        }
        return "nothing selected";
    }
    private void B_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_NextActionPerformed
        // TODO add your handling code here:
        String paketLangganan = getPaket();
        boolean agree = CB_Syarat.isSelected();
        
        FileInputStream proofstream = null;
        try {
            proofstream = new FileInputStream(proofFile);
        } catch (Exception ex) {
            //Logger.getLogger(Register_Tutor.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(agree && paketLangganan.compareTo("nothing selected") != 0 && proofstream != null){
            controller.PostMemberSubscription(paketLangganan, proofstream);
        }else{
            
        }
        
    }//GEN-LAST:event_B_NextActionPerformed

    private void B_UploadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_UploadFileActionPerformed
        // TODO add your handling code here:
        int returnValue = openFileChooser.showOpenDialog(this);
        
        if(returnValue == JFileChooser.APPROVE_OPTION){
            try{
                proofFile = openFileChooser.getSelectedFile();
                Label_UploadFile.setText(proofFile.getName());
            }catch(Exception e){
                Label_UploadFile.setText("Failed to load PDF file");
            }
        }else{
            Label_UploadFile.setText("No File Chosen");
        }
    }//GEN-LAST:event_B_UploadFileActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup BGroup_Subscription;
    private javax.swing.JButton B_Next;
    private javax.swing.JButton B_PaketLangganan;
    private javax.swing.JButton B_PaketNgambis;
    private javax.swing.JButton B_PaketSantai;
    private javax.swing.JButton B_UploadFile;
    private javax.swing.JCheckBox CB_Syarat;
    private javax.swing.JLabel Label_UploadFile;
    private javax.swing.JRadioButton RadioButton_PaketLangganan;
    private javax.swing.JRadioButton RadioButton_PaketNgambis;
    private javax.swing.JRadioButton RadioButton_PaketSantai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
