/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.QuestionMemberController;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author nabillaaura
 */
public class QuestionHistory extends javax.swing.JFrame {

    private QuestionMemberController controller;

    public QuestionHistory(QuestionMemberController controller, String name) {
        this.controller = controller;
        initComponents();
        Panel_Menu_Profil.setVisible(false);
        displayQuestion();
        Panel_Menu_Profil.setVisible(false);
        //SET NAMA
        Label_Username.setText(name);
    }
    /**
     * Creates new form SearchKategory
     */
    public QuestionHistory() {
        initComponents();
        Panel_Menu_Profil.setVisible(false);
        displayQuestion();
    }
    public void displayQuestion(){
        int numQuestion = Math.min(controller.questions.size(), 5); //MAX 10, kalau mau ditambah harus copy paste dulu
        for (int i = 0; i < numQuestion; i++){
            //SETTING SETIAP PERTANYAAN
            String judul_pertanyaan = controller.questions.get(i).title + Integer.toString(i);
            String content = controller.questions.get(i).getContent();
            boolean answered = true;
            
//           DISPLAY SETTING BEGIN
            javax.swing.JPanel display_Question = (javax.swing.JPanel) Panel_Question_detail.getComponent(i);
            
            javax.swing.JLabel judul = (javax.swing.JLabel) display_Question.getComponent(0);
            judul.setText(judul_pertanyaan);
            
            javax.swing.JTextArea content_ = (javax.swing.JTextArea) display_Question.getComponent(1);
            content_.setText(content);
            
            javax.swing.JLabel answered_ = (javax.swing.JLabel) display_Question.getComponent(2);
            answered_.setVisible(answered);
//            DISPLAY SETTING END
        }
        for (int i = numQuestion; i < 10; i++){
            Panel_Question_detail.getComponent(i).setVisible(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        Panel_Menu_Profil = new javax.swing.JPanel();
        B_Profil = new javax.swing.JButton();
        B_Logout = new javax.swing.JButton();
        Label_Username = new javax.swing.JLabel();
        Panel_Navbar = new javax.swing.JPanel();
        B_Pertanyaanku = new javax.swing.JButton();
        B_ProfilMenu = new javax.swing.JButton();
        B_Home = new javax.swing.JButton();
        Panel_Questions = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Panel_Question_detail = new javax.swing.JPanel();
        Question_1 = new javax.swing.JPanel();
        Label_Judul = new javax.swing.JLabel();
        Label_Content = new javax.swing.JTextArea();
        Label_Answered = new javax.swing.JLabel();
        Question_2 = new javax.swing.JPanel();
        Label_Judul1 = new javax.swing.JLabel();
        Label_Content1 = new javax.swing.JTextArea();
        Label_Answered1 = new javax.swing.JLabel();
        Question_3 = new javax.swing.JPanel();
        Label_Judul2 = new javax.swing.JLabel();
        Label_Content2 = new javax.swing.JTextArea();
        Label_Answered2 = new javax.swing.JLabel();
        Question_4 = new javax.swing.JPanel();
        Label_Judul3 = new javax.swing.JLabel();
        Label_Content3 = new javax.swing.JTextArea();
        Label_Answered3 = new javax.swing.JLabel();
        Question_5 = new javax.swing.JPanel();
        Label_Judul4 = new javax.swing.JLabel();
        Label_Content4 = new javax.swing.JTextArea();
        Label_Answered4 = new javax.swing.JLabel();
        Question_6 = new javax.swing.JPanel();
        Label_Judul5 = new javax.swing.JLabel();
        Label_Content5 = new javax.swing.JTextArea();
        Label_Answered5 = new javax.swing.JLabel();
        Question_7 = new javax.swing.JPanel();
        Label_Judul6 = new javax.swing.JLabel();
        Label_Content6 = new javax.swing.JTextArea();
        Label_Answered6 = new javax.swing.JLabel();
        Question_8 = new javax.swing.JPanel();
        Label_Judul7 = new javax.swing.JLabel();
        Label_Content7 = new javax.swing.JTextArea();
        Label_Answered7 = new javax.swing.JLabel();
        Question_9 = new javax.swing.JPanel();
        Label_Judul8 = new javax.swing.JLabel();
        Label_Content8 = new javax.swing.JTextArea();
        Label_Answered8 = new javax.swing.JLabel();
        Question_10 = new javax.swing.JPanel();
        Label_Judul9 = new javax.swing.JLabel();
        Label_Content9 = new javax.swing.JTextArea();
        Label_Answered9 = new javax.swing.JLabel();
        B_Delete_1 = new javax.swing.JButton();
        B_Delete_2 = new javax.swing.JButton();
        B_Delete_3 = new javax.swing.JButton();
        B_Delete_4 = new javax.swing.JButton();
        B_Delete_5 = new javax.swing.JButton();
        B_Delete_6 = new javax.swing.JButton();
        B_Delete_7 = new javax.swing.JButton();
        B_Delete_8 = new javax.swing.JButton();
        B_Delete_9 = new javax.swing.JButton();
        B_Delete_10 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(224, 187, 218));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Panel_Menu_Profil.setBackground(new java.awt.Color(255, 248, 248));
        Panel_Menu_Profil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_Menu_ProfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Panel_Menu_ProfilMouseExited(evt);
            }
        });

        B_Profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Profil2_default.png"))); // NOI18N
        B_Profil.setPreferredSize(new java.awt.Dimension(153, 52));
        B_Profil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_ProfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B_ProfilMouseExited(evt);
            }
        });
        B_Profil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ProfilActionPerformed(evt);
            }
        });

        B_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Logout_default.png"))); // NOI18N
        B_Logout.setPreferredSize(new java.awt.Dimension(153, 51));
        B_Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_LogoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B_LogoutMouseExited(evt);
            }
        });
        B_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_LogoutActionPerformed(evt);
            }
        });

        Label_Username.setFont(Label_Username.getFont().deriveFont(Label_Username.getFont().getSize()+7f));
        Label_Username.setText("Nuril K");

        javax.swing.GroupLayout Panel_Menu_ProfilLayout = new javax.swing.GroupLayout(Panel_Menu_Profil);
        Panel_Menu_Profil.setLayout(Panel_Menu_ProfilLayout);
        Panel_Menu_ProfilLayout.setHorizontalGroup(
            Panel_Menu_ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Menu_ProfilLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_Menu_ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(B_Profil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Label_Username))
                .addContainerGap())
        );
        Panel_Menu_ProfilLayout.setVerticalGroup(
            Panel_Menu_ProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_Menu_ProfilLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(Label_Username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B_Profil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(Panel_Menu_Profil, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, -1, -1));

        Panel_Navbar.setBackground(new java.awt.Color(224, 187, 218));
        Panel_Navbar.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, Color.BLACK));
        Panel_Navbar.setPreferredSize(new java.awt.Dimension(153, 108));
        Panel_Navbar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Panel_NavbarMouseEntered(evt);
            }
        });

        B_Pertanyaanku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Pertanyaanku_default.png"))); // NOI18N
        B_Pertanyaanku.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        B_Pertanyaanku.setBorderPainted(false);
        B_Pertanyaanku.setPreferredSize(new java.awt.Dimension(153, 51));
        B_Pertanyaanku.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                B_PertanyaankuFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                B_PertanyaankuFocusLost(evt);
            }
        });
        B_Pertanyaanku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_PertanyaankuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B_PertanyaankuMouseExited(evt);
            }
        });
        B_Pertanyaanku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_PertanyaankuActionPerformed(evt);
            }
        });

        B_ProfilMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Profil_default.png"))); // NOI18N
        B_ProfilMenu.setBorder(null);
        B_ProfilMenu.setPreferredSize(new java.awt.Dimension(101, 45));
        B_ProfilMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_ProfilMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B_ProfilMenuMouseExited(evt);
            }
        });
        B_ProfilMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ProfilMenuActionPerformed(evt);
            }
        });

        B_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Home_default.png"))); // NOI18N
        B_Home.setBorder(null);
        B_Home.setPreferredSize(new java.awt.Dimension(101, 77));
        B_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B_HomeMouseExited(evt);
            }
        });
        B_Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_HomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_NavbarLayout = new javax.swing.GroupLayout(Panel_Navbar);
        Panel_Navbar.setLayout(Panel_NavbarLayout);
        Panel_NavbarLayout.setHorizontalGroup(
            Panel_NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_NavbarLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(B_Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(B_Pertanyaanku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(B_ProfilMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        Panel_NavbarLayout.setVerticalGroup(
            Panel_NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_NavbarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Panel_NavbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(B_ProfilMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Pertanyaanku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B_Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel1.add(Panel_Navbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, -1));

        Panel_Questions.setBackground(new java.awt.Color(224, 187, 218));

        jScrollPane2.setBackground(new java.awt.Color(224, 187, 218));
        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.getVerticalScrollBar().setUnitIncrement(16);
        jScrollPane2.getVerticalScrollBar().setValue(jScrollPane2.getVerticalScrollBar().getMinimum() );

        Panel_Question_detail.setBackground(new java.awt.Color(224, 187, 218));
        Panel_Question_detail.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                Panel_Question_detailComponentResized(evt);
            }
        });
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        jPanel2Layout.rowHeights = new int[] {0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0, 10, 0};
        Panel_Question_detail.setLayout(jPanel2Layout);

        Question_1.setBackground(new java.awt.Color(255, 248, 248));
        Question_1.setPreferredSize(new java.awt.Dimension(500, 150));
        Question_1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_Judul.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label_Judul.setText("Judul 1");
        Question_1.add(Label_Judul, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 400, 30));

        Label_Content.setEditable(false);
        Label_Content.setBackground(new java.awt.Color(255, 248, 248));
        Label_Content.setColumns(20);
        Label_Content.setFont(Label_Content.getFont().deriveFont(Label_Content.getFont().getStyle() & ~java.awt.Font.BOLD));
        Label_Content.setLineWrap(true);
        Label_Content.setRows(3);
        Label_Content.setText("Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since t");
        Label_Content.setWrapStyleWord(true);
        Label_Content.setBorder(null);
        Label_Content.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Question_1.add(Label_Content, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 390, -1));

        Label_Answered.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/Icon_answered.png"))); // NOI18N
        Question_1.add(Label_Answered, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weighty = 1.3;
        Panel_Question_detail.add(Question_1, gridBagConstraints);

        Question_2.setBackground(new java.awt.Color(255, 248, 248));
        Question_2.setPreferredSize(new java.awt.Dimension(500, 150));
        Question_2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_Judul1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label_Judul1.setText("Judul 2");
        Question_2.add(Label_Judul1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 400, 30));

        Label_Content1.setEditable(false);
        Label_Content1.setBackground(new java.awt.Color(255, 248, 248));
        Label_Content1.setColumns(20);
        Label_Content1.setFont(Label_Content1.getFont().deriveFont(Label_Content1.getFont().getStyle() & ~java.awt.Font.BOLD));
        Label_Content1.setLineWrap(true);
        Label_Content1.setRows(3);
        Label_Content1.setText("Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since t");
        Label_Content1.setWrapStyleWord(true);
        Label_Content1.setBorder(null);
        Label_Content1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Question_2.add(Label_Content1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 390, -1));

        Label_Answered1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/Icon_answered.png"))); // NOI18N
        Question_2.add(Label_Answered1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.weighty = 1.3;
        Panel_Question_detail.add(Question_2, gridBagConstraints);

        Question_3.setBackground(new java.awt.Color(255, 248, 248));
        Question_3.setPreferredSize(new java.awt.Dimension(500, 150));
        Question_3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_Judul2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label_Judul2.setText("Judul 3");
        Question_3.add(Label_Judul2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 400, 30));

        Label_Content2.setEditable(false);
        Label_Content2.setBackground(new java.awt.Color(255, 248, 248));
        Label_Content2.setColumns(20);
        Label_Content2.setFont(Label_Content2.getFont().deriveFont(Label_Content2.getFont().getStyle() & ~java.awt.Font.BOLD));
        Label_Content2.setLineWrap(true);
        Label_Content2.setRows(3);
        Label_Content2.setText("Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since t");
        Label_Content2.setWrapStyleWord(true);
        Label_Content2.setBorder(null);
        Label_Content2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Question_3.add(Label_Content2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 390, -1));

        Label_Answered2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/Icon_answered.png"))); // NOI18N
        Question_3.add(Label_Answered2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.weighty = 1.3;
        Panel_Question_detail.add(Question_3, gridBagConstraints);

        Question_4.setBackground(new java.awt.Color(255, 248, 248));
        Question_4.setPreferredSize(new java.awt.Dimension(500, 150));
        Question_4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_Judul3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label_Judul3.setText("Judul 4");
        Question_4.add(Label_Judul3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 400, 30));

        Label_Content3.setEditable(false);
        Label_Content3.setBackground(new java.awt.Color(255, 248, 248));
        Label_Content3.setColumns(20);
        Label_Content3.setFont(Label_Content3.getFont().deriveFont(Label_Content3.getFont().getStyle() & ~java.awt.Font.BOLD));
        Label_Content3.setLineWrap(true);
        Label_Content3.setRows(3);
        Label_Content3.setText("Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since t");
        Label_Content3.setWrapStyleWord(true);
        Label_Content3.setBorder(null);
        Label_Content3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Question_4.add(Label_Content3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 390, -1));

        Label_Answered3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/Icon_answered.png"))); // NOI18N
        Question_4.add(Label_Answered3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.weighty = 1.3;
        Panel_Question_detail.add(Question_4, gridBagConstraints);

        Question_5.setBackground(new java.awt.Color(255, 248, 248));
        Question_5.setPreferredSize(new java.awt.Dimension(500, 150));
        Question_5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_Judul4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label_Judul4.setText("Judul 5");
        Question_5.add(Label_Judul4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 400, 30));

        Label_Content4.setEditable(false);
        Label_Content4.setBackground(new java.awt.Color(255, 248, 248));
        Label_Content4.setColumns(20);
        Label_Content4.setFont(Label_Content4.getFont().deriveFont(Label_Content4.getFont().getStyle() & ~java.awt.Font.BOLD));
        Label_Content4.setLineWrap(true);
        Label_Content4.setRows(3);
        Label_Content4.setText("Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since t");
        Label_Content4.setWrapStyleWord(true);
        Label_Content4.setBorder(null);
        Label_Content4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Question_5.add(Label_Content4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 390, -1));

        Label_Answered4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/Icon_answered.png"))); // NOI18N
        Question_5.add(Label_Answered4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.weighty = 1.3;
        Panel_Question_detail.add(Question_5, gridBagConstraints);

        Question_6.setBackground(new java.awt.Color(255, 248, 248));
        Question_6.setPreferredSize(new java.awt.Dimension(500, 150));
        Question_6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_Judul5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label_Judul5.setText("Judul 6");
        Question_6.add(Label_Judul5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 400, 30));

        Label_Content5.setEditable(false);
        Label_Content5.setBackground(new java.awt.Color(255, 248, 248));
        Label_Content5.setColumns(20);
        Label_Content5.setFont(Label_Content5.getFont().deriveFont(Label_Content5.getFont().getStyle() & ~java.awt.Font.BOLD));
        Label_Content5.setLineWrap(true);
        Label_Content5.setRows(3);
        Label_Content5.setText("Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since t");
        Label_Content5.setWrapStyleWord(true);
        Label_Content5.setBorder(null);
        Label_Content5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Question_6.add(Label_Content5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 390, -1));

        Label_Answered5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/Icon_answered.png"))); // NOI18N
        Question_6.add(Label_Answered5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.weighty = 1.3;
        Panel_Question_detail.add(Question_6, gridBagConstraints);

        Question_7.setBackground(new java.awt.Color(255, 248, 248));
        Question_7.setPreferredSize(new java.awt.Dimension(500, 150));
        Question_7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_Judul6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label_Judul6.setText("Judul 7");
        Question_7.add(Label_Judul6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 400, 30));

        Label_Content6.setEditable(false);
        Label_Content6.setBackground(new java.awt.Color(255, 248, 248));
        Label_Content6.setColumns(20);
        Label_Content6.setFont(Label_Content6.getFont().deriveFont(Label_Content6.getFont().getStyle() & ~java.awt.Font.BOLD));
        Label_Content6.setLineWrap(true);
        Label_Content6.setRows(3);
        Label_Content6.setText("Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since t");
        Label_Content6.setWrapStyleWord(true);
        Label_Content6.setBorder(null);
        Label_Content6.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Question_7.add(Label_Content6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 390, -1));

        Label_Answered6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/Icon_answered.png"))); // NOI18N
        Question_7.add(Label_Answered6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.weighty = 1.3;
        Panel_Question_detail.add(Question_7, gridBagConstraints);

        Question_8.setBackground(new java.awt.Color(255, 248, 248));
        Question_8.setPreferredSize(new java.awt.Dimension(500, 150));
        Question_8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_Judul7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label_Judul7.setText("Judul 8");
        Question_8.add(Label_Judul7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 400, 30));

        Label_Content7.setEditable(false);
        Label_Content7.setBackground(new java.awt.Color(255, 248, 248));
        Label_Content7.setColumns(20);
        Label_Content7.setFont(Label_Content7.getFont().deriveFont(Label_Content7.getFont().getStyle() & ~java.awt.Font.BOLD));
        Label_Content7.setLineWrap(true);
        Label_Content7.setRows(3);
        Label_Content7.setText("Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since t");
        Label_Content7.setWrapStyleWord(true);
        Label_Content7.setBorder(null);
        Label_Content7.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Question_8.add(Label_Content7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 390, -1));

        Label_Answered7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/Icon_answered.png"))); // NOI18N
        Question_8.add(Label_Answered7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.weighty = 1.3;
        Panel_Question_detail.add(Question_8, gridBagConstraints);

        Question_9.setBackground(new java.awt.Color(255, 248, 248));
        Question_9.setPreferredSize(new java.awt.Dimension(500, 150));
        Question_9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_Judul8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label_Judul8.setText("Judul 9");
        Question_9.add(Label_Judul8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 400, 30));

        Label_Content8.setEditable(false);
        Label_Content8.setBackground(new java.awt.Color(255, 248, 248));
        Label_Content8.setColumns(20);
        Label_Content8.setFont(Label_Content8.getFont().deriveFont(Label_Content8.getFont().getStyle() & ~java.awt.Font.BOLD));
        Label_Content8.setLineWrap(true);
        Label_Content8.setRows(3);
        Label_Content8.setText("Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since t");
        Label_Content8.setWrapStyleWord(true);
        Label_Content8.setBorder(null);
        Label_Content8.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Question_9.add(Label_Content8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 390, -1));

        Label_Answered8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/Icon_answered.png"))); // NOI18N
        Question_9.add(Label_Answered8, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 20;
        gridBagConstraints.weighty = 1.3;
        Panel_Question_detail.add(Question_9, gridBagConstraints);

        Question_10.setBackground(new java.awt.Color(255, 248, 248));
        Question_10.setPreferredSize(new java.awt.Dimension(500, 150));
        Question_10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_Judul9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Label_Judul9.setText("Judul 10");
        Question_10.add(Label_Judul9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 400, 30));

        Label_Content9.setEditable(false);
        Label_Content9.setBackground(new java.awt.Color(255, 248, 248));
        Label_Content9.setColumns(20);
        Label_Content9.setFont(Label_Content9.getFont().deriveFont(Label_Content9.getFont().getStyle() & ~java.awt.Font.BOLD));
        Label_Content9.setLineWrap(true);
        Label_Content9.setRows(3);
        Label_Content9.setText("Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since t");
        Label_Content9.setWrapStyleWord(true);
        Label_Content9.setBorder(null);
        Label_Content9.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Question_10.add(Label_Content9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 390, -1));

        Label_Answered9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/Icon_answered.png"))); // NOI18N
        Question_10.add(Label_Answered9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 22;
        gridBagConstraints.weighty = 1.3;
        Panel_Question_detail.add(Question_10, gridBagConstraints);

        B_Delete_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Delete_default.png"))); // NOI18N
        B_Delete_1.setPreferredSize(new java.awt.Dimension(70, 26));
        B_Delete_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_Delete_1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B_Delete_1MouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        Panel_Question_detail.add(B_Delete_1, gridBagConstraints);

        B_Delete_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Delete_default.png"))); // NOI18N
        B_Delete_2.setPreferredSize(new java.awt.Dimension(70, 26));
        B_Delete_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_Delete_2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B_Delete_2MouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        Panel_Question_detail.add(B_Delete_2, gridBagConstraints);

        B_Delete_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Delete_default.png"))); // NOI18N
        B_Delete_3.setPreferredSize(new java.awt.Dimension(70, 26));
        B_Delete_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_Delete_3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B_Delete_3MouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        Panel_Question_detail.add(B_Delete_3, gridBagConstraints);

        B_Delete_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Delete_default.png"))); // NOI18N
        B_Delete_4.setPreferredSize(new java.awt.Dimension(70, 26));
        B_Delete_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_Delete_4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B_Delete_4MouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        Panel_Question_detail.add(B_Delete_4, gridBagConstraints);

        B_Delete_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Delete_default.png"))); // NOI18N
        B_Delete_5.setPreferredSize(new java.awt.Dimension(70, 26));
        B_Delete_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_Delete_5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B_Delete_5MouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        Panel_Question_detail.add(B_Delete_5, gridBagConstraints);

        B_Delete_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Delete_default.png"))); // NOI18N
        B_Delete_6.setPreferredSize(new java.awt.Dimension(70, 26));
        B_Delete_6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_Delete_6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B_Delete_6MouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        Panel_Question_detail.add(B_Delete_6, gridBagConstraints);

        B_Delete_7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Delete_default.png"))); // NOI18N
        B_Delete_7.setPreferredSize(new java.awt.Dimension(70, 26));
        B_Delete_7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_Delete_7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B_Delete_7MouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        Panel_Question_detail.add(B_Delete_7, gridBagConstraints);

        B_Delete_8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Delete_default.png"))); // NOI18N
        B_Delete_8.setPreferredSize(new java.awt.Dimension(70, 26));
        B_Delete_8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_Delete_8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B_Delete_8MouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 18;
        Panel_Question_detail.add(B_Delete_8, gridBagConstraints);

        B_Delete_9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Delete_default.png"))); // NOI18N
        B_Delete_9.setPreferredSize(new java.awt.Dimension(70, 26));
        B_Delete_9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_Delete_9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B_Delete_9MouseExited(evt);
            }
        });
        B_Delete_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_Delete_9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 20;
        Panel_Question_detail.add(B_Delete_9, gridBagConstraints);

        B_Delete_10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Delete_default.png"))); // NOI18N
        B_Delete_10.setPreferredSize(new java.awt.Dimension(70, 26));
        B_Delete_10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                B_Delete_10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                B_Delete_10MouseExited(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 22;
        Panel_Question_detail.add(B_Delete_10, gridBagConstraints);

        jScrollPane2.setViewportView(Panel_Question_detail);

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setText("Pertanyaanku");

        javax.swing.GroupLayout Panel_QuestionsLayout = new javax.swing.GroupLayout(Panel_Questions);
        Panel_Questions.setLayout(Panel_QuestionsLayout);
        Panel_QuestionsLayout.setHorizontalGroup(
            Panel_QuestionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 890, Short.MAX_VALUE)
            .addGroup(Panel_QuestionsLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Panel_QuestionsLayout.setVerticalGroup(
            Panel_QuestionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_QuestionsLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.add(Panel_Questions, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 890, 410));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_PertanyaankuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_B_PertanyaankuFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_B_PertanyaankuFocusGained

    private void B_PertanyaankuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_B_PertanyaankuFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_B_PertanyaankuFocusLost

    private void B_PertanyaankuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_PertanyaankuMouseEntered
        // TODO add your handling code here:
        Panel_Menu_Profil.setVisible(false);
        B_Pertanyaanku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Pertanyaanku_hover.png")));
    }//GEN-LAST:event_B_PertanyaankuMouseEntered

    private void B_PertanyaankuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_PertanyaankuMouseExited
        // TODO add your handling code here:
        B_Pertanyaanku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Pertanyaanku_default.png")));
    }//GEN-LAST:event_B_PertanyaankuMouseExited

    private void B_PertanyaankuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_PertanyaankuActionPerformed
        // TODO add your handling code here:
        controller.ShowQuestionHistory();
    }//GEN-LAST:event_B_PertanyaankuActionPerformed

    private void B_ProfilMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_ProfilMenuMouseEntered
        // TODO add your handling code here:
        B_ProfilMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Profil_hover.png")));
        Panel_Menu_Profil.setVisible(true);
    }//GEN-LAST:event_B_ProfilMenuMouseEntered

    private void B_ProfilMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_ProfilMenuMouseExited
        // TODO add your handling code here:
        B_ProfilMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Profil_default.png")));
    }//GEN-LAST:event_B_ProfilMenuMouseExited

    private void B_ProfilMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ProfilMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_ProfilMenuActionPerformed

    private void B_HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_HomeMouseEntered
        // TODO add your handling code here:
        B_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Home_hover.png")));
    }//GEN-LAST:event_B_HomeMouseEntered

    private void B_HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_HomeMouseExited
        // TODO add your handling code here:
        B_Home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Home_default.png")));
    }//GEN-LAST:event_B_HomeMouseExited

    private void B_HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_HomeActionPerformed
        // TODO add your handling code here:
        controller.Home();
    }//GEN-LAST:event_B_HomeActionPerformed

    private void Panel_NavbarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_NavbarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_NavbarMouseEntered

    private void B_ProfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_ProfilMouseEntered
        // TODO add your handling code here:
        B_ProfilMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Profil_hover.png")));
        Panel_Menu_Profil.setVisible(true);
        B_Profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Profil2_hover.png")));

    }//GEN-LAST:event_B_ProfilMouseEntered

    private void B_ProfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_ProfilMouseExited
        // TODO add your handling code here:
        B_ProfilMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Profil_default.png")));
        B_Profil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Profil2_default.png")));
    }//GEN-LAST:event_B_ProfilMouseExited

    private void B_ProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ProfilActionPerformed
        // TODO add your handling code here:
        controller.ProfileMember();
    }//GEN-LAST:event_B_ProfilActionPerformed

    private void B_LogoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_LogoutMouseEntered
        // TODO add your handling code here:
        B_ProfilMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Profil_hover.png")));
        Panel_Menu_Profil.setVisible(true);
        B_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Logout_hover.png")));
    }//GEN-LAST:event_B_LogoutMouseEntered

    private void B_LogoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_LogoutMouseExited
        // TODO add your handling code here:
        B_ProfilMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Profil_default.png")));
        B_Logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Logout_default.png")));
    }//GEN-LAST:event_B_LogoutMouseExited

    private void B_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_LogoutActionPerformed
        // TODO add your handling code here:
        int dialogButton = JOptionPane.showConfirmDialog (null, "Anda yakin akan keluar?","Keluar",JOptionPane.YES_NO_OPTION);
        if(dialogButton == JOptionPane.YES_OPTION) {
            controller.Logout();}
        else {remove(dialogButton);}
    }//GEN-LAST:event_B_LogoutActionPerformed

    private void Panel_Menu_ProfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_Menu_ProfilMouseEntered
        // TODO add your handling code here:
        B_ProfilMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Profil_hover.png")));
    }//GEN-LAST:event_Panel_Menu_ProfilMouseEntered

    private void Panel_Menu_ProfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_Menu_ProfilMouseExited
        // TODO add your handling code here:
        B_ProfilMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Profil_default.png")));
        Panel_Menu_Profil.setVisible(false);

    }//GEN-LAST:event_Panel_Menu_ProfilMouseExited

    private void Panel_Question_detailComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_Panel_Question_detailComponentResized
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_Question_detailComponentResized

    private void B_Delete_1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Delete_1MouseEntered
        // TODO add your handling code here:
        B_Delete_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Delete_hover.png")));
    }//GEN-LAST:event_B_Delete_1MouseEntered

    private void B_Delete_1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Delete_1MouseExited
        // TODO add your handling code here:
        B_Delete_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_Delete_default.png")));
    }//GEN-LAST:event_B_Delete_1MouseExited

    private void B_Delete_2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Delete_2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_B_Delete_2MouseEntered

    private void B_Delete_2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Delete_2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_B_Delete_2MouseExited

    private void B_Delete_3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Delete_3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_B_Delete_3MouseEntered

    private void B_Delete_3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Delete_3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_B_Delete_3MouseExited

    private void B_Delete_4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Delete_4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_B_Delete_4MouseEntered

    private void B_Delete_4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Delete_4MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_B_Delete_4MouseExited

    private void B_Delete_5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Delete_5MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_B_Delete_5MouseEntered

    private void B_Delete_5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Delete_5MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_B_Delete_5MouseExited

    private void B_Delete_6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Delete_6MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_B_Delete_6MouseEntered

    private void B_Delete_6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Delete_6MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_B_Delete_6MouseExited

    private void B_Delete_7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Delete_7MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_B_Delete_7MouseEntered

    private void B_Delete_7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Delete_7MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_B_Delete_7MouseExited

    private void B_Delete_8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Delete_8MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_B_Delete_8MouseEntered

    private void B_Delete_8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Delete_8MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_B_Delete_8MouseExited

    private void B_Delete_9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Delete_9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_B_Delete_9MouseEntered

    private void B_Delete_9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Delete_9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_B_Delete_9MouseExited

    private void B_Delete_10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Delete_10MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_B_Delete_10MouseEntered

    private void B_Delete_10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B_Delete_10MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_B_Delete_10MouseExited

    private void B_Delete_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_Delete_9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_B_Delete_9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuestionHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuestionHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuestionHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuestionHistory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuestionHistory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Delete_1;
    private javax.swing.JButton B_Delete_10;
    private javax.swing.JButton B_Delete_2;
    private javax.swing.JButton B_Delete_3;
    private javax.swing.JButton B_Delete_4;
    private javax.swing.JButton B_Delete_5;
    private javax.swing.JButton B_Delete_6;
    private javax.swing.JButton B_Delete_7;
    private javax.swing.JButton B_Delete_8;
    private javax.swing.JButton B_Delete_9;
    private javax.swing.JButton B_Home;
    private javax.swing.JButton B_Logout;
    private javax.swing.JButton B_Pertanyaanku;
    private javax.swing.JButton B_Profil;
    private javax.swing.JButton B_ProfilMenu;
    private javax.swing.JLabel Label_Answered;
    private javax.swing.JLabel Label_Answered1;
    private javax.swing.JLabel Label_Answered2;
    private javax.swing.JLabel Label_Answered3;
    private javax.swing.JLabel Label_Answered4;
    private javax.swing.JLabel Label_Answered5;
    private javax.swing.JLabel Label_Answered6;
    private javax.swing.JLabel Label_Answered7;
    private javax.swing.JLabel Label_Answered8;
    private javax.swing.JLabel Label_Answered9;
    private javax.swing.JTextArea Label_Content;
    private javax.swing.JTextArea Label_Content1;
    private javax.swing.JTextArea Label_Content2;
    private javax.swing.JTextArea Label_Content3;
    private javax.swing.JTextArea Label_Content4;
    private javax.swing.JTextArea Label_Content5;
    private javax.swing.JTextArea Label_Content6;
    private javax.swing.JTextArea Label_Content7;
    private javax.swing.JTextArea Label_Content8;
    private javax.swing.JTextArea Label_Content9;
    private javax.swing.JLabel Label_Judul;
    private javax.swing.JLabel Label_Judul1;
    private javax.swing.JLabel Label_Judul2;
    private javax.swing.JLabel Label_Judul3;
    private javax.swing.JLabel Label_Judul4;
    private javax.swing.JLabel Label_Judul5;
    private javax.swing.JLabel Label_Judul6;
    private javax.swing.JLabel Label_Judul7;
    private javax.swing.JLabel Label_Judul8;
    private javax.swing.JLabel Label_Judul9;
    private javax.swing.JLabel Label_Username;
    private javax.swing.JPanel Panel_Menu_Profil;
    private javax.swing.JPanel Panel_Navbar;
    private javax.swing.JPanel Panel_Question_detail;
    private javax.swing.JPanel Panel_Questions;
    private javax.swing.JPanel Question_1;
    private javax.swing.JPanel Question_10;
    private javax.swing.JPanel Question_2;
    private javax.swing.JPanel Question_3;
    private javax.swing.JPanel Question_4;
    private javax.swing.JPanel Question_5;
    private javax.swing.JPanel Question_6;
    private javax.swing.JPanel Question_7;
    private javax.swing.JPanel Question_8;
    private javax.swing.JPanel Question_9;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
