/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.SignUpController;

/**
 *
 * @author nabillaaura
 */
public class Register_Member extends javax.swing.JFrame {

    /**
     * Creates new form Register_Member
     */
    public Register_Member() {
        initComponents();
    }
    
    SignUpController controller;
    public Register_Member(SignUpController controller) {
        this.controller = controller;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TF_UsernameMember = new javax.swing.JTextField();
        TF_NamaLengkapMember = new javax.swing.JTextField();
        PF_reTypePassword = new javax.swing.JPasswordField();
        PF_Password = new javax.swing.JPasswordField();
        B_CreateAccountMember = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TF_Biodata = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TF_UsernameMember.setBackground(new java.awt.Color(224, 187, 218));
        jPanel1.add(TF_UsernameMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 225, 270, 35));

        TF_NamaLengkapMember.setBackground(new java.awt.Color(224, 187, 218));
        jPanel1.add(TF_NamaLengkapMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 190, 270, 35));

        PF_reTypePassword.setBackground(new java.awt.Color(224, 187, 218));
        PF_reTypePassword.setToolTipText("");
        jPanel1.add(PF_reTypePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 295, 270, 40));

        PF_Password.setBackground(new java.awt.Color(224, 187, 218));
        PF_Password.setToolTipText("");
        PF_Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PF_PasswordActionPerformed(evt);
            }
        });
        jPanel1.add(PF_Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 260, 270, 35));

        B_CreateAccountMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/B_CreateAccount.png"))); // NOI18N
        B_CreateAccountMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_CreateAccountMemberActionPerformed(evt);
            }
        });
        jPanel1.add(B_CreateAccountMember, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 140, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jLabel2.setText("*Tuliskan beberapa hal tentang kamu!");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 380, -1, 20));

        TF_Biodata.setBackground(new java.awt.Color(224, 187, 218));
        TF_Biodata.setColumns(20);
        TF_Biodata.setLineWrap(true);
        TF_Biodata.setRows(3);
        jScrollPane1.setViewportView(TF_Biodata);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 337, 270, 80));

        jLabel1.setBackground(new java.awt.Color(224, 187, 218));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/Icon/Background_RegisterMember.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_CreateAccountMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_CreateAccountMemberActionPerformed
        String username = TF_UsernameMember.getText();
        String nama = TF_NamaLengkapMember.getText();
        String password = PF_reTypePassword.getText();
        String rePassword = PF_Password.getText();
        String bio = TF_Biodata.getText();
        
        boolean isValid = !username.isEmpty() && !nama.isEmpty() 
                && (password.compareTo(rePassword) == 0);
        if(isValid)
            controller.RegisterUser(username, nama, password, bio);
    }//GEN-LAST:event_B_CreateAccountMemberActionPerformed

    private void PF_PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PF_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PF_PasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register_Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_Member().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_CreateAccountMember;
    private javax.swing.JPasswordField PF_Password;
    private javax.swing.JPasswordField PF_reTypePassword;
    private javax.swing.JTextArea TF_Biodata;
    private javax.swing.JTextField TF_NamaLengkapMember;
    private javax.swing.JTextField TF_UsernameMember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
